project: 
  title: &project_title alphasocket/dockerized-toolbox
  codename: &project_codename toolbox
  description: All required cli in one container

#
# Build process
# Creates dockerfile and file used in it
#
build:
  envvars:
    name: *project_codename
    cmd: "sleep 999"
    # Varni
    paths:
      binaries:
        folder: /usr/local/bin

#
# Setup process injected in dockerfile
#
setup:
  # Setup env 
  envvars:
    dependencies:
      php7_2: php@php7_2 php-curl@php7_2 php-dom@php7_2 php-gd@php7_2 php-gettext@php7_2 php-iconv@php7_2 php-json@php7_2 php-mbstring@php7_2 php-mysqli@php7_2 php-opcache@php7_2 php-openssl@php7_2 php-pdo@php7_2 php-pdo_dblib@php7_2 php-pdo_mysql@php7_2 php-pdo_pgsql@php7_2 php-pdo_sqlite@php7_2 php-pear@php7_2 php-pgsql@php7_2 php-phar@php7_2 php-phpdbg@php7_2 php-posix@php7_2 php-session@php7_2 php-soap@php7_2 php-sockets@php7_2 php-sqlite3@php7_2 php-xml@php7_2 php-zip@php7_2 php-zlib
      php7_0: php@php7_0 php-curl@php7_0 php-dom@php7_0 php-gd@php7_0 php-gettext@php7_0 php-iconv@php7_0 php-json@php7_0 php-mbstring@php7_0 php-mcrypt@php7_0 php-mysqli@php7_0 php-opcache@php7_0 php-openssl@php7_0 php-pdo@php7_0 php-pdo_dblib@php7_0 php-pdo_mysql@php7_0 php-pdo_pgsql@php7_0 php-pdo_sqlite@php7_0 php-pear@php7_0 php-pgsql@php7_0 php-phar@php7_0 php-phpdbg@php7_0 php-posix@php7_0 php-session@php7_0 php-soap@php7_0 php-sockets@php7_0 php-sqlite3@php7_0 php-xml@php7_0 php-zip@php7_0 php-zlib
      runtime: bash htop git mysql-client fcgi nodejs nodejs-npm python python3 py-pip $SETUP_DEPENDENCIES_PHP
  processes:
    - title: "Setup repository"
      commands:
        - curl -fsSL https://php.codecasts.rocks/php-alpine.rsa.pub -o /etc/apk/keys/php-alpine.rsa.pub
        - echo '@php7_2 https://php.codecasts.rocks/v3.7/php-7.2' >> /etc/apk/repositories
        - echo '@php7_0 https://php.codecasts.rocks/v3.7/php-7.0' >> /etc/apk/repositories
        
    - title: "Install extra binaries"
      commands:
        - apk add --no-cache $SETUP_DEPENDENCIES_PHP
        # Git
        - curl -fsSL https://raw.githubusercontent.com/AlphaSocket/git-get-latest-release/master/get-latest-release -o $BUILD_PATHS_BINARIES_FOLDER/git-get-latest-release
        - chmod +x $BUILD_PATHS_BINARIES_FOLDER/git-get-latest-release
        
        # PHP
        - curl -fsSL https://phar.phpunit.de/phpunit.phar -o $BUILD_PATHS_BINARIES_FOLDER/phpunit.phar
        - curl -fsSL http://static.phpmd.org/php/latest/phpmd.phar -o $BUILD_PATHS_BINARIES_FOLDER/phpmd.phar
        - curl -fsSL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o $BUILD_PATHS_BINARIES_FOLDER/phpcs.phar
        - curl -fsSL http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o $BUILD_PATHS_BINARIES_FOLDER/php-cs-fixer.phar
        - curl -fsSL https://getcomposer.org/composer.phar -o $BUILD_PATHS_BINARIES_FOLDER/composer.phar
        # Wordpress
        - curl -fsSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o $BUILD_PATHS_BINARIES_FOLDER/wp-cli.phar
        # Magento
        - curl -fsSL https://files.magerun.net/n98-magerun-latest.phar -o $BUILD_PATHS_BINARIES_FOLDER/n98-magerun.phar
        
        - curl -fsSL https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -o $BUILD_PATHS_BINARIES_FOLDER/modman
        
        - MAGECONFIGSYNC_LATEST=$(git-get-latest-release https://github.com/punkstar/mageconfigsync )
        - curl -fsSL https://github.com/punkstar/mageconfigsync/releases/download/$MAGECONFIGSYNC_LATEST/mageconfigsync-${MAGECONFIGSYNC_LATEST}.phar -o $BUILD_PATHS_BINARIES_FOLDER/mageconfigsync.phar
        
        # Kubernetes
        - KUBECTL_LATEST=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        - curl -fsSL https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_LATEST/bin/linux/amd64/kubectl -o $BUILD_PATHS_BINARIES_FOLDER/kubectl
        
        - curl -fsSL https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -o $BUILD_PATHS_BINARIES_FOLDER/minikube
        
        - KOPS_LATEST=$(git-get-latest-release https://github.com/kubernetes/kops )
        - curl -fsSL https://github.com/kubernetes/kops/releases/download/$KOPS_LATEST/kops-linux-amd64 -o $BUILD_PATHS_BINARIES_FOLDER/kops
        
        - ARGO_LATEST=$(git-get-latest-release https://github.com/argoproj/argo )
        - curl -fsSL https://github.com/argoproj/argo/releases/download/$ARGO_LATEST/argo-linux-amd64 -o $BUILD_PATHS_BINARIES_FOLDER/argo
        
        # OnePassword
        - mkdir /tmp/op
        - curl -fsSL https://cache.agilebits.com/dist/1P/op/pkg/v0.4/op_linux_amd64_v0.4.zip -o /tmp/op/op_linux_amd64_v0.4.zip
        - unzip /tmp/op/op_linux_amd64_v0.4.zip -d /tmp/op
        - mv /tmp/op/op $BUILD_PATHS_BINARIES_FOLDER/op
        - rm -r /tmp/op
        
        # Op
        - chmod -R +x /usr/local/bin

#
# Config process run just before the entrypoint
#
test:
  processes:
    #
    # Starting
    #
    - title: "Testing container readiness"
      commands:
        - TEST_CONTAINER_MAIN_ID=$(
            docker run
              -d --name=$TEST_CONTAINER_NAME
              ${BUILD_USER}/${BUILD_NAME}:${BUILD_VERSION}
          )
        - TEST_CONDITION="docker exec $TEST_CONTAINER_MAIN_ID docker-rediness-test"
        - TEST_BREAK_CONDITION='[ "$(docker inspect -f '{{.State.Running}}' "$TEST_CONTAINER_MAIN_ID")" != "true" ]'
        - MAX_TRIES=300
        - SECONDS_BETWEEN_TRIES=1
        - c=0
        - while ! eval "$TEST_CONDITION"; 
          do 
            if [ $c -ge ${MAX_TRIES} ] || eval "$TEST_BREAK_CONDITION" ; then
                echo "Error $TEST_CONTAINER_NAME container failed, printing logs and exiting\n";
                docker logs $TEST_CONTAINER_MAIN_ID;
                exit 1;
              else
                c=$(($c + 1));
            fi;
            echo "Try $c failed"; 
            sleep ${SECONDS_BETWEEN_TRIES}; 
          done && echo "### Container ready \n"

    # 
    # Run nginx
    # 
    - title: "Testing binaries"
      commands:
        - docker exec $TEST_CONTAINER_MAIN_ID n98-magerun.phar --version
        - docker exec $TEST_CONTAINER_MAIN_ID kubectl --version
